### ISSUE TITLE
How to unpack a sequence?

### ISSUE THREAD

**Issue by Hirrolot** [boostorg/preprocessor#30]
I want `(a)(b)(c)` -> `a b c`. Is there a library function for such a problem?

**Comment by eldiener** [comment]
The construct `(a)(b)(c)` is a 'seq'. You can use BOOST_PP_SEQ_FOR_EACH to manipulate the elements of a 'seq' as you like.

**Comment by Hirrolot** [comment]
Alright, thank you.
